# This file was generated by GoReleaser. DO NOT EDIT.
class Golintui < Formula
  desc "A simple terminal UI for golangci-lint"
  homepage "https://github.com/nakabonne/golintui"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nakabonne/golintui/releases/download/v0.1.1/golintui_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "9e82d2ec880d175134cb7180053f89b6223cf76873158ba4fa292a8052e16063"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nakabonne/golintui/releases/download/v0.1.1/golintui_0.1.1_Linux_x86_64.tar.gz"
      sha256 "e75e11a97b88f3bb1dc387e43eeab873620548fa68e6365b2837e0367684355d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nakabonne/golintui/releases/download/v0.1.1/golintui_0.1.1_Linux_arm64.tar.gz"
        sha256 "3b63ade9c8d693364a8a04147c1d636fcab6a0e59197ccd9976add6676e948e7"
      else
        url "https://github.com/nakabonne/golintui/releases/download/v0.1.1/golintui_0.1.1_Linux_armv6.tar.gz"
        sha256 "68f8709d8ebd82f259905a3d169fc819b80036145073b47a38f4bf8206704353"
      end
    end
  end

  def install
    bin.install "golintui"
  end
end
